const fs = require('fs');
const {getDbDateNow} = require('./utility')
const {ActivityLog: ActivityLogs} = require('../models/Auth/ActivityLog')

let date = new Date();
//let filename = `${date.getFullYear()} ${date.getMonth()} ${date.getDate()}`

 const getCurrentDate = () => {
    const t = new Date();
    const date = ('0' + t.getDate()).slice(-2);
    const month = ('0' + (t.getMonth() + 1)).slice(-2);
    const year = t.getFullYear();
    return `${year}${month}${date}`;
  }

  let filename = 'Logs/' + getCurrentDate() + '.txt';


// Log data generated by code i.e infos and exceptions
const logData = (data) =>{
    let stream = fs.createWriteStream(filename, {flags:'a'});
    let eventTime = new Date().toISOString().replace('T', ' ').split('.')[0];
    stream.write( eventTime + ': ' + data + "\n \n");
stream.end();
}

const logUserActivity = async (user_id, module_item_id, activity_type, is_success, record_id=null) =>{
  try{
      const event_date = getDbDateNow()
      const log_data = {user_id, module_item_id, activity_type, is_success, record_id, event_date}

      await ActivityLogs.create(log_data)
  }catch(err){
    logData('logUserActivity: ' + err)
  }
}

module.exports = {
  logData,
  logUserActivity
}